### PR TITLE
Made a few adjustments.

### PR DESCRIPTION
**Pull request by arlCode**
I enabled the user to input their map name and explained how to use the program on start-up. I also made a few spelling corrections.

### CODE REVIEW

**Comment by arlCode** [comment]
Removed __pycache__ folders and placed a Python.gitignore file inside the program to prevent further issues.

**Comment by arlCode** [comment]
Updated the AUTHORS.rst and I have renamed the file to .gitignore.

**Comment by arlCode** [comment]
Alrght, updated the AUTHORS.rst and renamed .gitignore.

**Comment by gregkrsak** [comment]
Did you want to keep going with this? Or start over?... either way

**Comment by arlCode** [comment]
I'd like to continue if that is possible. I'm learning a new language in class: Java. I'm trying to adapt everything I've learned from you thus far. Is there anything else you'd like me to do?

**Comment by gregkrsak** [comment]
I think it would be best to close this. I'm still interested in your contributions (very much so); however, I think having more-granular commits (and maybe even pull requests) would be a bit more productive.

**Pull request closed without merging**
